<?php if(!empty($resultados_pagina)): ?>
<div class="w-xxxx-12">
    
    <div class="w-xxxx-12 cont_widget_carrusel _carrusel  carrusel_<?=$carrusel['code']?>">
    <?php foreach($resultados_pagina as $data): ?>
      <div class="_li_carrusel">
          <?php if(!empty($data['url'])): ?>
            <a href="<?=$data['url']?>" target="_blank">
          <?php endif; ?>
              <?php echo makeHTMLImg($data['foto'],"","","","class='image_100'"); ?>
              <?php if(!empty($data['url'])): ?>
              </a>
          <?php endif; ?>
      </div> 
    <?php endforeach ;?>

    </div>
</div>
<?php $responsivo = json_decode($carrusel['responsivo'],true); ?>
<script>
$(window).load(function(){
$('.carrusel_<?=$carrusel['code']?>').slick({
      infinite: <?=($carrusel['infinito'] == 1 ? 'true':'false')?>,
      slidesToShow: <?=$carrusel['visible']?>,
      slidesToScroll: <?=$carrusel['scroll']?>,
      dots: <?=($carrusel['dots'] == 1 ? 'true':'false')?>,
      <?php if(!empty($responsivo)): ?>
      responsive: [
        <?php foreach($responsivo as $r): ?>
          <?php if(!empty($r['width']) && !empty($r['scroll']) && !empty($r['visible'])): ?>
          {
            breakpoint: <?=$r['width']; ?>,
            settings: {
              slidesToShow: <?=$r['visible']; ?>,
              slidesToScroll: <?=$r['scroll']; ?>,
            }
          },
        <?php endif; ?>
        <?php endforeach;?>
         
      ]
        <?php endif; ?>
    });
});
</script>
<?php endif; ?>