<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?> </div>
        <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin"><?= _carrusel("Administrar carruseles") ?></h1>
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
    
                  <a href="<?php echo $MyRequest->url(ADMIN_CARRUSEL_FORM); ?>" class="_btn_new"><?= __('Nuevo') ?></a>
            </div>
        </div>

        <div  class="w-xxxx-12 cont_gral_admin cont_carrusel">
        <table id="jqGrid"></table>
        <div id="jqGridPager"></div>
        </div>
    </div>
</div>

<script>
$(window).load(function(){
    var isGridMobile = ($(window).width() <= 767 ? true : false);

    $("#jqGrid").GridAdmin({
        search : false,
        entity : 'carrusel',
        redirectOnSelectRow:true,
        gridPager : "#jqGridPager",
        btnSearch: "#btsSearchGridAdmin",
        redirectPath : '<?=$MyRequest->link(ADMIN_CARRUSEL_FOTOS)?>',
        pathData : '<?=$MyRequest->url(ADMIN_CARRUSEL_LIST)?>',
        error : "<?=_('No hay registros')?>",
        deleteFunction : "carrusel_DeleteCarrusel",
        colModel: [
            { label: '<?=_('ID')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('Callback')?>', name: 'callback',  hidden:true, width: 50 },
            { label: '<?=_('Status')?>', name: 'status',  hidden:true, width: 50 },
            { label: '<?=_('Fecha')?>', name: 'createdAt', hidden:isGridMobile,width: 200},
            { label: '<?=_('Nombre')?>', name: 'nombre',hidden:isGridMobile, width: 250 },
            { label: '<?=_('Codigo')?>', name: 'code', width: 250 },
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 200, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones 
            }
        ],
        subGrid: false,
        width:920
    });
 });

 function creadorDeBotones(cellvalue, options, rowObject) {
    
    var id = options.rowId; 
     
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton1 = '<a href="<?=$MyRequest->link(ADMIN_CARRUSEL_FORM)?>?id=' + id + '&callback='+rowObject.callback+'" class="btn_adm_editar"><span class="icon icon-editar"> </span></a> ';
    var boton2 = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';
    var boton3 = '<a class="btn_adm_editar_items" href="<?php echo $MyRequest->link(ADMIN_CARRUSEL_FOTOS)?>?id=' + id + '&callback='+rowObject.callback+'"><i class="icon icon-imagen"> </i></a>';
    return boton1 + boton2 + boton3;
}

</script>
